### ISSUE TITLE
Add ways to get contact information

### ISSUE THREAD

**Issue by mscherer** [JabberSPAM/blacklist#25]
I have recently received a bunch of spam from  servers, and following the docs here, I am trying to get their contact information using XEP-0157. However, I am unable to find a easy way to extract that on Conversation (the client I use at the moment). Search results on google, ddg are cluttered by server modules related results and the XEP, and Github search suffer from the same fate. 

I stumbled on poezio who seems to support it with a plugin, but it took me a while. 

I also found that the list on https://list.jabber.at/ display the information, but that's opt-in. Xmpp observatory do not display (but it could be added there).

So I think that the project could benefit from a few pointers on how to get the information, as I am surely not the only one who struggle. Or maybe just a quick script. I tried to hack my way with netcat, but XMPP is a bit more complex than HTTP and I haven't yet found a curl for xmpp, but I barely searched)

**Comment by licaon-kter** [comment]
Dropping some stanzas into the XML console of Gajim: https://xmpp.org/extensions/xep-0157.html#xmpp should be enough? 

Conversations is not targeted at such tasks.

**Comment by mscherer** [comment]
I agree, the idea of typing xml on my android keyboard make me shiver. However, while Gajim has the feature (and that's the one I would have used), it could be useful to have the list of clients that allow that.

Would such a list be a good idea for that repository or is there another location that would be more fitting ?

**Comment by mdosch** [comment]
You could also kindly ask your favorite clients devs to include a feature to retrieve 0157 contact info, like I did for [profanity](https://github.com/profanity-im/profanity/issues/1524). If you can provide the feature yourself, even better.

**Comment by ge0rg** [comment]
Thanks to the magic of [DOAP](https://xmpp.org/extensions/xep-0453.html), it's now possible to automatically query the list of clients for 0157 support. This has been implemented in the [XMPP.org software list](https://xmpp.org/software/) under "More Filters / Supported XEPs".
