### ISSUE TITLE
default.rs

### ISSUE THREAD

**Issue by quite** [JabberSPAM/blacklist#7]
I'm getting a lot of spam from this jid domain. I've sent a mail to various abuse addresses. We'll see...

**Comment by ge0rg** [comment]
Please provide details on which addresses you've contacted and what kind of data you provided, also the exact date of the contact, according to <https://github.com/JabberSPAM/blacklist#addition-to-blacklist>. I'd like to see the progress tracked in some place, and this issue is probably okay for it.

**Comment by quite** [comment]
```
To: abuse@ninet.rs
Cc: bc@default.rs, abuse@itplatforma.com, hostmaster@providus.rs
Date: Tue, 10 Sep 2019 12:20:00 +0200
Subject: spam over xmpp (jabber) from default.rs                                                                                                  

Hallo,

I'm getting lots of spam over XMPP chat (https://en.wikipedia.org/wiki/XMPP)
from the JID domain default.rs

Looking up the SRV records to find the actual XMPP server:

  _xmpp-server._tcp.default.rs. 3521 IN   SRV     10 0 5269 jabber.default.rs.
  _xmpp-client._tcp.default.rs. 3522 IN   SRV     10 0 5222 jabber.default.rs.
  jabber.default.rs.            182  IN   A       176.104.107.121

This IP belongs to you, NINET.

CC:ing other possibly related actors.

best regards
--
Daniel
lublin.se
```

**Comment by mightyBroccoli** [comment]
Do you have any logs proving the reported behavior? Just to further underline this report and to help the admin/s of default.rs possibly solving this issue.

**Comment by quite** [comment]
No response at all so far. Admin of the server might be @bculibrk

**Comment by quite** [comment]
A person that claims to be admin of default.rs says they have turned off in-band registration completely for now. Moreover, they say that due to the spamming, their DNS hoster even removed the server A record from DNS (which the XMPP SRV record refers to). I was surprised that they were not in control of the zone on which apex the XMPP server is fronted... But if this is all correct, hopefully spamming won't beginning again once that A record is put back in place.

**Comment by ge0rg** [comment]
The default.rs server has been completely shut down after another spam report.

**Comment by quite** [comment]
Oh rly? Did you report @ge0rg ?

**Comment by hantu85** [comment]
From my experience in the last few days, it looks like default.rs is back up and sending spam again.

**Comment by blackbit42** [comment]
```
$ grep -oP "[[:alpha:]]+?@default\.rs" .weechat/logs/irc.bitlbee.\&bitlbee.weechatlog | sort -u
anin@default.rs
arkadiyviktorovich@default.rs
bankshopk@default.rs
bc@default.rs
bobinskij@default.rs
boraone@default.rs
caymortq@default.rs
challengemine@default.rs
chaves@default.rs
chineseprodigy@default.rs
corradoe@default.rs
european@default.rs
fordregas@default.rs
generalisimus@default.rs
guidemaster@default.rs
gvozdika@default.rs
habibich@default.rs
i@default.rs
inal@default.rs
johnjackjonesp@default.rs
locallbitcoins@default.rs
masterica@default.rs
meriniver@default.rs
moreprodukt@default.rs
netgrad@default.rs
patriotik@default.rs
p@default.rs
princespar@default.rs
rn@default.rs
rothschild@default.rs
saberfont@default.rs
sendspend@default.rs
stakanuga@default.rs
sxaceisxs@default.rs
t@default.rs
tebepizda@default.rs
terapevt@default.rs
uf@default.rs
ulanovu@default.rs
vaguely@default.rs
volisinos@default.rs
woods@default.rs
```

How can I get in touch with the admin of default.rs?

**Comment by quite** [comment]
@blackbit42 i have an email address to them, you can contact me through github profile -> website -> contact
(i also threw them an email myself now, linking to this issue)

**Comment by ge0rg** [comment]
I can confirm, 400+ bot sightings from default.rs on my server in the last two weeks. There is a new [XEP-0157](https://xmpp.org/extensions/xep-0157.html) contact address on default.rs, so I've sent complaints and a list of JIDs in that direction.
